Update kuebrnetes.yml

diff --git a/kuebrnetes.yml b/kuebrnetes.yml
--- a/kuebrnetes.yml
+++ b/kuebrnetes.yml
@@ -6,6 +6,31 @@ data:
   PalWorldSettings.ini: |
     [/Script/Pal.PalGameWorldSettings]
     OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="Default Palworld Server",ServerDescription="",AdminPassword="",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=False,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
+  entrypoint.sh: |
+    #!/bin/bash
+    STEAMCMD="/home/steam/steamcmd/steamcmd.sh"
+    OK="[ OK ]"
+    FAIL="[ FAIL ]"
+    install() {
+        $STEAMCMD +login anonymous +app_update 2394010 validate +quit || bash -c 'echo "$FAIL Failed to install PalWorld" && exit 1';
+        echo "$OK Installed PalWorld";
+    }
+    update() {
+        if [ "$AUTO_UPDATE" = "true" ]; then
+            $STEAMCMD +login anonymous +app_update 2394010 validate +quit || bash -c 'echo "$FAIL Failed to update PalWorld" && exit 1';
+            echo "$OK Updated PalWorld";
+        fi
+    }
+    main() {
+        echo "$OK Container Started"
+        if [ ! -f "/home/steam/Steam/steamapps/common/PalServer/PalServer.sh" ]; then
+            install
+        else
+            update
+        fi
+        ./PalServer.sh
+    }
+    main
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim
@@ -43,7 +68,10 @@ spec:
         volumeMounts:
         - name: saved
           mountPath: /home/steam/Steam/steamapps/common/PalServer
-        - name: saved
+        - name: settings
+          mountPath: /home/steam/Steam/steamapps/common/PalServer/entrypoint.sh
+          subPath: entrypoint.sh
+        - name: settings
           mountPath: /home/steam/Steam/steamapps/common/PalServer/PalWorldSettings.ini
           subPath: PalWorldSettings.ini
       volumes:
